Feature/jwt authorization with db
DaniilAndCo/vehicle-sales-project pull request #3
Opened 2021-08-06 14:28 UTC by DaniilAndCo

I created Spring boot application with dependencies for working with MySql databases, Hibernate and Spring Security.
Connected project database and made Jwt authorization with the database, user table.

2021-08-06 14:30 UTC, DaniilAndCo commented
The next my step is registration. I'll do it up to the next week and then we can have calling.

2021-08-12 12:14 UTC, asenchuk requested changes

2021-08-12 14:11 UTC, DaniilAndCo commented
waiting your review on project structure

2021-08-17 06:49 UTC, asenchuk approved these changes
some changes are needed but let's move them to tickets

2021-08-17 06:49 UTC, asenchuk commented on pom.xml
> +	<name>spring-boot-initial</name>
Should be the name of your project. `spring-boot-initial` is just a placeholder.

2021-08-17 06:49 UTC, asenchuk commented on src/main/java/com/github/daniilandco/vehicle_sales_project/controller/request/RegisterRequest.java
> +                SecurityConfig.passwordEncoder().encode(this.getPassword()),
ideally, this method should be moved to some kind of `UserService` where PasswordEncoder is injected and isn't statically referenced.

2021-08-17 07:05 UTC, merged