Feature/ad user interaction
DaniilAndCo/vehicle-sales-project pull request #4
Opened 2021-08-21 12:59 UTC by DaniilAndCo

adding ability to users to create and maintain ads, using migration for db version control and project structure refactoring

2021-08-21 13:00 UTC, DaniilAndCo commented
waiting for review on done things

2021-08-21 13:02 UTC, DaniilAndCo commented
the next things I am gonna implement:
-ability to assign make of a vihicle in the right way
-storing profile and ads photos and manage this

2021-08-24 09:31 UTC, asenchuk requested changes

2021-08-24 09:31 UTC, asenchuk commented on src/main/java/com/github/daniilandco/vehicle_sales_project/config/SecurityConfig.java
> +    private static final int encryptionStrength = 12;
if it's a constant it should be named like this `ENCRYPTION_STRENGTH`

2021-08-24 09:31 UTC, asenchuk commented on src/main/java/com/github/daniilandco/vehicle_sales_project/controller/UserController.java
> +    }
why not moving ad-related endpoints to `AdController` with a base context `/ads`?

2021-09-03 10:29 UTC, asenchuk commented
CategoryRequest seems to be not added to the repo

2021-09-15 11:50 UTC, merged